backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "shoots"
    label: "Shoots"
    folder: "content/shoots"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        hint: "Name for this shoot (D Family, Baby B, Tati Beauty Palette)"
      - label: "Date"
        name: "date"
        widget: "datetime"
        hint: "Date added to the site or date of the shoot"
      - label: "Category"
        name: "category"
        widget: "select"
        multiple: true
        options: ["Family", "Announcement"]
      - label: "Featured Image"
        name: "featured_image"
        widget: "object"
        fields:
          - { name: src, label: Image, widget: image }
          - {
              name: alt,
              label: Alt text,
              widget: string,
              hint: Description of the image,
            }
        hint: "The main image to show on the homepage"
      - label: "Images"
        name: "galleryImages"
        widget: "list"
        fields:
          - { name: src, label: Image, widget: image }
          - {
              name: alt,
              label: Alt text,
              widget: string,
              hint: Description of the image,
            }
      - label: "Description"
        name: "body"
        widget: "markdown"
        hint: "Any text you'd like to use to describe this shoot"
